#!/usr/bin/env python3

"""
Stores url and selected text in a provided file
Note: This script must be called from qutebrowser
"""

import os
import sys
import argparse
import time

TIME_FORMAT = "<%Y-%m-%d %a %H:%M>"

argparser = argparse.ArgumentParser(description=__doc__)
argparser.add_argument("--file", dest="file", type=str, help="Org filepath")


def qute_command(command):
    """send commands to qutebrowser"""
    with open(os.environ["QUTE_FIFO"], "w") as fifo:
        fifo.write(command + "\n")
        fifo.flush


def format_node(heading, url, body, tag):
    node = "* {h}        :{t}:\n {u}\n {b}\n  CAPTURED:{c}\n".format(
        h=heading, t=tag, u=url, b=body, c=time.strftime(TIME_FORMAT)
    )
    return node


def main(args):
    if not os.getenv("QUTE_URL") or not args.file:
        argparser.print_help()
        return 1

    title = os.getenv("QUTE_TITLE")
    url = os.getenv("QUTE_URL")
    content = os.getenv("QUTE_SELECTED_TEXT")

    new_node = format_node(title, url, content, "BROWSER")

    f = open(os.path.expanduser(args.file), "a")
    f.write(new_node)
    qute_command('message-info "captured ' + title)
    return 0


if __name__ == "__main__":
    sys.exit(main(argparser.parse_args()))
